export interface Country {
  en: string; // for search input
  ja: string; // for display
}

export const COUNTRIES: Country[] = [
  // 東アジア
  { en: "China", ja: "中国" },
  { en: "Japan", ja: "日本" },
  { en: "South Korea", ja: "韓国" },
  { en: "North Korea", ja: "北朝鮮" },
  { en: "Mongolia", ja: "モンゴル" },
  { en: "Taiwan", ja: "台湾" },
  // 東南アジア
  { en: "Brunei", ja: "ブルネイ" },
  { en: "Cambodia", ja: "カンボジア" },
  { en: "Indonesia", ja: "インドネシア" },
  { en: "Laos", ja: "ラオス" },
  { en: "Malaysia", ja: "マレーシア" },
  { en: "Myanmar", ja: "ミャンマー" },
  { en: "Philippines", ja: "フィリピン" },
  { en: "Singapore", ja: "シンガポール" },
  { en: "Thailand", ja: "タイ" },
  { en: "Timor-Leste", ja: "東ティモール" },
  { en: "Vietnam", ja: "ベトナム" },
  // 南アジア
  { en: "Bangladesh", ja: "バングラデシュ" },
  { en: "Bhutan", ja: "ブータン" },
  { en: "India", ja: "インド" },
  { en: "Maldives", ja: "モルディブ" },
  { en: "Nepal", ja: "ネパール" },
  { en: "Pakistan", ja: "パキスタン" },
  { en: "Sri Lanka", ja: "スリランカ" },
  // 中央アジア
  { en: "Kazakhstan", ja: "カザフスタン" },
  { en: "Kyrgyzstan", ja: "キルギスタン" },
  { en: "Tajikistan", ja: "タジキスタン" },
  { en: "Turkmenistan", ja: "トルクメニスタン" },
  { en: "Uzbekistan", ja: "ウズベキスタン" },
  // 中東
  { en: "Bahrain", ja: "バーレーン" },
  { en: "Egypt", ja: "エジプト" },
  { en: "Iran", ja: "イラン" },
  { en: "Iraq", ja: "イラク" },
  { en: "Israel", ja: "イスラエル" },
  { en: "Jordan", ja: "ヨルダン" },
  { en: "Kuwait", ja: "クウェート" },
  { en: "Lebanon", ja: "レバノン" },
  { en: "Oman", ja: "オマーン" },
  { en: "Palestine", ja: "パレスチナ" },
  { en: "Qatar", ja: "カタール" },
  { en: "Saudi Arabia", ja: "サウジアラビア" },
  { en: "Syria", ja: "シリア" },
  { en: "Turkey", ja: "トルコ" },
  { en: "United Arab Emirates", ja: "アラブ首長国連邦" },
  { en: "Yemen", ja: "イエメン" },
  // ヨーロッパ
  { en: "Albania", ja: "アルバニア" },
  { en: "Armenia", ja: "アルメニア" },
  { en: "Austria", ja: "オーストリア" },
  { en: "Azerbaijan", ja: "アゼルバイジャン" },
  { en: "Belarus", ja: "ベラルーシ" },
  { en: "Belgium", ja: "ベルギー" },
  { en: "Bosnia and Herzegovina", ja: "ボスニア・ヘルツェゴビナ" },
  { en: "Bulgaria", ja: "ブルガリア" },
  { en: "Croatia", ja: "クロアチア" },
  { en: "Cyprus", ja: "キプロス" },
  { en: "Czech Republic", ja: "チェコ" },
  { en: "Denmark", ja: "デンマーク" },
  { en: "Estonia", ja: "エストニア" },
  { en: "Finland", ja: "フィンランド" },
  { en: "France", ja: "フランス" },
  { en: "Georgia", ja: "ジョージア" },
  { en: "Germany", ja: "ドイツ" },
  { en: "Greece", ja: "ギリシャ" },
  { en: "Hungary", ja: "ハンガリー" },
  { en: "Iceland", ja: "アイスランド" },
  { en: "Ireland", ja: "アイルランド" },
  { en: "Italy", ja: "イタリア" },
  { en: "Kosovo", ja: "コソボ" },
  { en: "Latvia", ja: "ラトビア" },
  { en: "Lithuania", ja: "リトアニア" },
  { en: "Luxembourg", ja: "ルクセンブルク" },
  { en: "Malta", ja: "マルタ" },
  { en: "Moldova", ja: "モルドバ" },
  { en: "Montenegro", ja: "モンテネグロ" },
  { en: "Netherlands", ja: "オランダ" },
  { en: "North Macedonia", ja: "北マケドニア" },
  { en: "Norway", ja: "ノルウェー" },
  { en: "Poland", ja: "ポーランド" },
  { en: "Portugal", ja: "ポルトガル" },
  { en: "Romania", ja: "ルーマニア" },
  { en: "Russia", ja: "ロシア" },
  { en: "Serbia", ja: "セルビア" },
  { en: "Slovakia", ja: "スロバキア" },
  { en: "Slovenia", ja: "スロベニア" },
  { en: "Spain", ja: "スペイン" },
  { en: "Sweden", ja: "スウェーデン" },
  { en: "Switzerland", ja: "スイス" },
  { en: "Ukraine", ja: "ウクライナ" },
  { en: "United Kingdom", ja: "イギリス" },
  // アフリカ
  { en: "Algeria", ja: "アルジェリア" },
  { en: "Angola", ja: "アンゴラ" },
  { en: "Cameroon", ja: "カメルーン" },
  { en: "Cote d'Ivoire", ja: "コートジボワール" },
  { en: "DR Congo", ja: "コンゴ民主共和国" },
  { en: "Ethiopia", ja: "エチオピア" },
  { en: "Ghana", ja: "ガーナ" },
  { en: "Kenya", ja: "ケニア" },
  { en: "Libya", ja: "リビア" },
  { en: "Madagascar", ja: "マダガスカル" },
  { en: "Morocco", ja: "モロッコ" },
  { en: "Mozambique", ja: "モザンビーク" },
  { en: "Nigeria", ja: "ナイジェリア" },
  { en: "Senegal", ja: "セネガル" },
  { en: "South Africa", ja: "南アフリカ" },
  { en: "Sudan", ja: "スーダン" },
  { en: "Tanzania", ja: "タンザニア" },
  { en: "Tunisia", ja: "チュニジア" },
  { en: "Uganda", ja: "ウガンダ" },
  { en: "Zimbabwe", ja: "ジンバブエ" },
  // 北アメリカ・カリブ
  { en: "Canada", ja: "カナダ" },
  { en: "Cuba", ja: "キューバ" },
  { en: "Dominican Republic", ja: "ドミニカ共和国" },
  { en: "Haiti", ja: "ハイチ" },
  { en: "Jamaica", ja: "ジャマイカ" },
  { en: "Mexico", ja: "メキシコ" },
  { en: "United States", ja: "アメリカ" },
  // 中米・南米
  { en: "Argentina", ja: "アルゼンチン" },
  { en: "Bolivia", ja: "ボリビア" },
  { en: "Brazil", ja: "ブラジル" },
  { en: "Chile", ja: "チリ" },
  { en: "Colombia", ja: "コロンビア" },
  { en: "Costa Rica", ja: "コスタリカ" },
  { en: "Ecuador", ja: "エクアドル" },
  { en: "Guatemala", ja: "グアテマラ" },
  { en: "Honduras", ja: "ホンジュラス" },
  { en: "Panama", ja: "パナマ" },
  { en: "Paraguay", ja: "パラグアイ" },
  { en: "Peru", ja: "ペルー" },
  { en: "Uruguay", ja: "ウルグアイ" },
  { en: "Venezuela", ja: "ベネズエラ" },
  // オセアニア
  { en: "Australia", ja: "オーストラリア" },
  { en: "Fiji", ja: "フィジー" },
  { en: "New Zealand", ja: "ニュージーランド" },
  { en: "Papua New Guinea", ja: "パプアニューギニア" },
];
